---
title: "Reproducible Research Assignment 1"
date: "12/8/2020"
output: html_document
---


# Load and process data 

```{r echo=TRUE}
unzip(zipfile="activity.zip")
activity <-read.csv("activity.csv")
```


# What is the mean total number of steps taken per day?

## Total number of steps taken per day
```{r echo=TRUE}
stepsPerDay <-tapply(activity$steps, activity$date, sum, na.rm=TRUE)
```

## Histogram of total number of steps taken each day
```{r echo=TRUE}
hist(stepsPerDay, xlab="Number of Steps", main="Total number of steps taken each dat")
```

## Mean and median of total steps taken per day
```{r echo=TRUE}
median(stepsPerDay)
mean(stepsPerDay)
```

# What is the average daily activity pattern?

## Time series plot of the 5-minute interval and the average number of steps taken
```{r echo=TRUE}
averagePerDay <-tapply(activity$steps, activity$interval, mean, na.rm=TRUE)
plot(averagePerDay, xlab="5-Minute Interval", ylab = "Average Number of Steps", type="l", main="Average Number of steps taken Per Day Per 5-Minute Interval")
```

